feat: new index pages, data. and form
permanar/limosia-admin-panel pull request #16
Opened 2023-07-23 06:44 UTC by putradnata

- Add: Airport Index Page
- Add: Users Index Page
- Add: Car Class Index Page
- Add: Airport Create Page (including form)
- Add: Icons
- Add: Some placeholders data for Airport, Car Classes, and Users
- Update: Sidebar Menu Items

2023-07-23 15:21 UTC, permanar requested changes

2023-07-23 15:21 UTC, permanar commented on pages/admin/airport/[id].tsx
While it's not really recommended approach, you can't leave an empty file like this.

Please at least do the bare minimum to make this page works (i.e.: add export default and return empty JSX).

2023-07-23 15:21 UTC, permanar commented on pages/admin/airport/create.tsx
> +    };
Please move this code outside the `CreateAirport()` function (at root level).

2023-07-23 15:21 UTC, permanar commented on pages/admin/carclass/[id].tsx
Please do the same as the airport page above.

2023-07-23 15:21 UTC, permanar commented on pages/admin/carclass/create.tsx
Please do the same as the airport page above.

2023-07-23 15:21 UTC, permanar commented on pages/admin/orders/[id].tsx
Please do the same as the airport page above.

2023-07-23 15:21 UTC, permanar commented on pages/admin/orders/index.tsx
Please do the same as the airport page above.

2023-07-23 15:21 UTC, permanar commented on pages/admin/users/[id].tsx
Please do the same as the airport page above.

2023-07-23 15:21 UTC, permanar commented on pages/admin/users/create.tsx
Please do the same as the airport page above.

2023-07-24 16:48 UTC, putradnata commented
Resolve #17

2023-07-25 15:32 UTC, closed without merging